from apifunctions.functions import makeDeleteRequest
from apifunctions.functions import makeGetRequest
from apifunctions.functions import makePostRequest
from apifunctions.functions import makePatchRequest
from apifunctions.functions import makePutRequest
from apifunctions.functions import makeSoapRequest
